#!/bin/bash
#
# An example deployment script that creates a README.md from the
# update-checkout_and_deploy.sh script, and copies it to the path specified by
# `git config deployment.path`.

sed -n -e '2,/^$/s%^# *%%p' ./update-checkout_and_deploy.sh > README.md

echo '### Source code, `update-checkout_and_deploy.sh`' >> README.md
echo '```bash' >> README.md
cat update-checkout_and_deploy.sh >> README.md
echo '```' >> README.md

echo '### Example deployment script, `deploy-master`' >> README.md
echo '```bash' >> README.md
cat deploy-master >> README.md
echo '```' >> README.md

if [ -z "$(git config deployment.path)" ]; then
    echo "No deployment path found. Execute 'git config deployment.path PATH'." >&2
    exit 1
else
    cp * "$(git config deployment.path)/"
fi

exit 0
